### ISSUE TITLE
Please port to fabric.

### ISSUE THREAD

**Issue by disgracedmf** [edoren/SkinChanger#10]
Adding high-res support to skins and capes would be awesome and also porting this awesome mod to fabric would be amazing!
Also for the high-res capes/skins it should work with the url.

**Comment by edoren** [comment]
From version 1.20.4-0.6.1 this is supported on Fabric and NeoForge
https://www.curseforge.com/minecraft/mc-mods/skinchanger/files/all?page=1&pageSize=20&gameVersionTypeId=4
