### ISSUE TITLE
[Request] A Transshipment Request.

### ISSUE THREAD

**Issue by At87668** [edoren/SkinChanger#30]
I want to transshipment this mod to [MCMOD](mcmod.cn) , is it okay?
I really like this mod, it is much more powerful than the current mainstream skin plugins and mods. [(SkinsRestorer ?)](https://www.spigotmc.org/resources/skinsrestorer.2124/)
But it's so unwell known.

**Comment by edoren** [comment]
It's ok as long as you are able to maintain it and don't forget to mention the original Curse Forge URL:
https://www.curseforge.com/minecraft/mc-mods/skinchanger

**Comment by At87668** [comment]
thanks
