### ISSUE TITLE
capes are bugged

### ISSUE THREAD

**Issue by Volt-0001** [edoren/SkinChanger#36]
capes only show in the corner
![2023-12-24_18 34 16](https://github.com/edoren/SkinChanger/assets/127156221/b068ab14-fd4f-45d2-b664-0a66cc14f640)
![capaenderman](https://github.com/edoren/SkinChanger/assets/127156221/f7275201-fd42-4cb9-8145-1da8ffdebdce)

**Comment by edoren** [comment]
I think this is not a valid cape file, it should be one like this one:
https://laby.net/cape/de4a8ad0267f4fc0f41a732ebcf10ec9
You can right click on the download button and use that URL:
https://laby.net/texture/download/de4a8ad0267f4fc0f41a732ebcf10ec9.png
You can find more capes here:
https://laby.net/capes
