### ISSUE TITLE
can`t load skin from file

### ISSUE THREAD

**Issue by Lavshyak** [edoren/SkinChanger#37]
endless loading of the skin when I load it from a file.
```
/skin set file:///C:/Users/USER/Downloads/steve.png
``` 
![steve](https://github.com/edoren/SkinChanger/assets/73601154/76f48379-d448-465b-ba5b-241339617674)

**Comment by edoren** [comment]
Hello! You are using a file:/// reference URL, this is not supported, you should use an http:// URL, E.g:
https://s.namemc.com/i/9cbd3f6105659d4b.png
