### ISSUE TITLE
command just doesn't work

### ISSUE THREAD

**Issue by V0idKing** [edoren/SkinChanger#38]
command simply doesn't work, it appears as if the command doesn't exist telling you to type /help
![Captura de tela 2024-03-07 210509](https://github.com/edoren/SkinChanger/assets/69680415/afebf64c-92ba-4fe2-98fb-a42934770f49)

**Comment by edoren** [comment]
Hello, please fill this information to have more context of the bug:

**Describe the bug**
A clear and concise description of what the bug is.

**Mod Loader**
 - [ ] Forge
 - [ ] NeoForge
 - [ ] Fabric

**Version Info (Please complete the following information)**
 - Mod Loader: [e.g. 51.0.22]
 - SkinChanger Version: [e.g. 0.6.1]
 - Minecraft Version: [e.g. 1.21.0]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by FrijoTico** [comment]
Describe the bug
i have the same problem basically says the command doesnt exist even though the mod is installed properly

Mod Loader
Version Info (Please complete the following information)

Mod Loader: Forge 43.3.8
SkinChanger Version: 0.5.0
Minecraft Version: 1.19.2
 

To Reproduce
inserting any of this mod commands 


Logs
[Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.](https://mclo.gs/bJDp10T)

Screenshots
![image](https://github.com/edoren/SkinChanger/assets/175082728/f7010550-1d69-40e5-b247-37d50a3e6972)

**Comment by edoren** [comment]
Hello! 

To be able to modify others skin using the `/skin player [NAME] set [URL]` command you should be `op` on the server.

Also as note the URL is invalid, it should point to a PNG file not the page of the skin

**Comment by edoren** [comment]
Try with this version and check if that fixes it for you:
https://github.com/edoren/SkinChanger/releases/download/v0.5.2/skin_changer-0.5.2.jar

**Comment by FrijoTico** [comment]
still nothing  also i checked the log and there is this error [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: Could not find parent com/google/gson/reflect/TypeToken for class me/edoren/skin_changer/server/SkinProviderController$1

**Comment by edoren** [comment]
If that error is still happening you should still have an old version, that code was removed for the one I provided
https://github.com/edoren/SkinChanger/commit/77847f8d10b91b1eeee9d4e22a00f56ec5a8ea4a

**Comment by edoren** [comment]
If that error is still happening you should still have an old version, that code was removed for the one I provided
https://github.com/edoren/SkinChanger/commit/77847f8d10b91b1eeee9d4e22a00f56ec5a8ea4a

**Comment by edoren** [comment]
It's possible that Arclight might introduce some Mixing incompatibilities, but I saw on the previous logs you provided that it was working before for other users, which leads me to believe it might be a permissions issue.

Please provide some logs again, in this case the `latest.log` file that is inside the `logs` folder of the server.

**Comment by edoren** [comment]
Nvm, I found the issue, please try with this build:
https://github.com/edoren/SkinChanger/releases/download/v0.5.3/skin_changer-1.19-0.5.3.jar

**Comment by Jelavi** [comment]
Hi, I have the same error using arclight, however I am using version 1.20.1, could you help me?

![image](https://github.com/user-attachments/assets/43c658af-b31f-42df-bd8b-ec94c94720e6)

**Comment by edoren** [comment]
@Jelavi can you provide more information about the issue, which URL are you using? Can you provide some logs?

**Comment by edoren** [comment]
This should be fixed in latest release, clsing this for now
