### ISSUE TITLE
1.16.3 dont work

### ISSUE THREAD

**Issue by DogEnix** [edoren/SkinChanger#4]
https://gyazo.com/1678944cec75564e63a09220bdbe885d

**Comment by edoren** [comment]
Mmm this is an in client warning I might fix this in the next bugfix release

**Comment by edoren** [comment]
Please use version 0.2.1+

**Comment by edoren** [comment]
Fixed in https://github.com/edoren/SkinChanger/commit/5ab92ed513c30f99b3d614f7ae3aaf851f50396f
