### ISSUE TITLE
Skin using URL won't load

### ISSUE THREAD

**Issue by FlyingMonsty** [edoren/SkinChanger#42]
**Describe the bug**

**Mod Loader**
 - [v] Forge
 - [ ] NeoForge
 - [ ] Fabric

**Version Info (Please complete the following information)**
 - Mod Loader: 47.2.0
 - SkinChanger Version: 0.6.0
 - Minecraft Version: 1.20.1

**To Reproduce**
1. Try "/skin set https://i.imgur.com/F5wsNKu.png" and "/skin set https://imgur.com/F5wsNKu", neither work
2. Says 'Skin loaded successfully' however no change is seen

**Expected behavior**
Expected the skin to change into the one posted on imgur

**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**
![2024-08-01_19 41 41](https://github.com/user-attachments/assets/071c7750-f275-40ed-89e8-6cb587373881)

**Comment by asatico** [comment]
hey how's it going !
I'm experiencing the same bug.
Did you manage to fix it?

**Comment by SunnySpyZ** [comment]
![Screenshot 2024-10-06 020341](https://github.com/user-attachments/assets/c7559f9e-4f03-4496-b870-18f6696b9965)
Hello, I tried all the methods you said but I still can't change the skin

**Comment by edoren** [comment]
Hello! As of now Imgur links do not work as it does not provide a direct link to an image. A direct link is something like this:

https://s.namemc.com/i/fe95468706d33d04.png

I'm seeing the option to support Imgur in the future as multiple people seem to use it but have to see how viable it is.
