### ISSUE TITLE
Commands wont work, what image links are you supposed to even use if its not imgur or the skindex?

### ISSUE THREAD

**Issue by LowChromieHomie** [edoren/SkinChanger#43]
**Describe the bug**
dont work

**Mod Loader**
 - [47.3.0] Forge
 - [ ] NeoForge
 - [ ] Fabric

**Version Info (Please complete the following information)**
 - Mod Loader: [e.g. 51.0.22]
 - SkinChanger Version: [0.6.0]
 - Minecraft Version: [1.20.1]

**To Reproduce**

**Expected behavior**
dont work

**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**

**Comment by edoren** [comment]
Imgur does not provide a direct link to an URL which makes it impossible to use from their links, there is another way using an API they provide, I created this ticket for it #45

You should be able to use Skindex by providing the direct link for the image file

E.g: For this https://www.skindex.pro/boy-hoodie-white-ripped-jeans-classic-model/ you can should use the "Image Link" that is at the bottom:

https://www.skindex.pro/static/skins/boy-hoodie-white-ripped-jeans-classic-model-QTTMnTae9pn7tC4JnY5RGd.png

That one should work.

**Comment by edoren** [comment]
This will be tracked on #45
