### ISSUE TITLE
Command bug

### ISSUE THREAD

**Issue by RavendelR** [edoren/SkinChanger#44]
**Describe the bug**
The mod doesn't load correctly i join the server with the mod on and i can't access the commands 

**Mod Loader**
 - [x] Forge
 
**Version Info (Please complete the following information)**
 - Mod Loader: recommanded
 - SkinChanger Version: 0.6.1
 - Minecraft Version: 1.20.1

**To Reproduce**
1. install the mod 
2. start your server
3. doesn't work

**Expected behavior**
I would like to have access to commands but it doesn't show when autocompleting
**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**
![image](https://github.com/user-attachments/assets/27ba8655-e980-4de5-a769-47cb6a1e091f)

**Comment by edoren** [comment]
Hello, can you please provide some logs to identify the issue?, which mod loader are you using, Forge, NeoForge, Fabric?

**Comment by RavendelR** [comment]
hello i just need to restart the server to make the commands work again so there is no bug !
