### ISSUE TITLE
1.16.4 crash when opening inventory with just enough items

### ISSUE THREAD

**Issue by enderplayer2002** [edoren/SkinChanger#5]
Only mods installed: Latest Jei and Latest SkinChanger
logs below

[crash-2021-01-24_13.52.57-client.txt](https://github.com/edoren/SkinChanger/files/5862707/crash-2021-01-24_13.52.57-client.txt)
[latest.log](https://github.com/edoren/SkinChanger/files/5862703/latest.log)
[debug.log](https://github.com/edoren/SkinChanger/files/5862704/debug.log)

**Comment by edoren** [comment]
Thanks for the logs, I'll take a look into it for the next bug fix release

**Comment by edoren** [comment]
I was not able to reproduce it. Added some checkings to avoid that possible issue on latest v0.2.1
