### ISSUE TITLE
1.12.2 version

### ISSUE THREAD

**Issue by ummmyey** [edoren/SkinChanger#6]
like idk im so sorry if i sholdn't be 
posting this here
..this mod is so great 
but i just wanted to ask could you please make a
1.12.2 version too..and i think a lot more of the users would 
probably appretiate it cause like there are a million mods and modpacks that
new versions don't support so a lot of us can't update our versions 
but you know bro this mod is so handy
sorry again if i wasn't supposed to post this here in issues
but please have 1.12.2 in mind

**Comment by edoren** [comment]
Sorry no, from 1.12 to 1.16 there are a lot of API changes that will require a rewrite of the current code.
