### ISSUE TITLE
Mod issue on server 1.16.5 (mohist)

### ISSUE THREAD

**Issue by DearFox** [edoren/SkinChanger#7]
I am using the 1.16.5 version of the game. The mod works in a single player game. However, on the server on which the mod is also installed, you cannot write commands and they do not work.
(the first time I started, I could write commands while on the server, but they just didn't work saying: "Unknown command. Type" / help "for help.")

there are no errors in the server console regarding this mod.

**Comment by DearFox** [comment]
![image](https://user-images.githubusercontent.com/59219907/109945709-9476c280-7ce8-11eb-84b9-ecf4ecefe96a.png)
a screenshot showing that the mod is on the server, but the commands are not defined

**Comment by edoren** [comment]
I see you are trying to execute the command from the console, currently, it only works from within the game

**Comment by iver0** [comment]
Can confirm, commands don't work on Mohist
And it seems like it's one of the many Mohist issues, not the mod issue... I'd recommend staying away from it, there's even reports that it's actually malicious but idk, what I do know, it does mess with my friend's server, just not worth it man
