### ISSUE TITLE
Crash in 1.15.2 version

### ISSUE THREAD

**Issue by WordStormRose** [edoren/SkinChanger#8]
Hello, I keep receiving this same crash when trying to test out the 1.15 version of your mod to add to my modpack. Is there a way you can fix it?

Have a wonderful day!

Teithor
[crash-2021-03-26_20.33.06-client.txt](https://github.com/edoren/SkinChanger/files/6215067/crash-2021-03-26_20.33.06-client.txt)

**Comment by edoren** [comment]
Just to confirm, what version of the mod are you using?

**Comment by WordStormRose** [comment]
release 0.1.0
